name: Unit Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  checkstyle:
      name: runner / checkstyle
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: dbelyaev/action-checkstyle@v0.5.1
          with:
            github_token: ${{ secrets.github_token }}
            reporter: local
            level: warning
            fail_on_error: true
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run Compile Tests
      run: ./gradlew assembleRelease
    - name: Run Unit Tests
      run: ./gradlew :app:testProdReleaseUnitTest :wear:testProdReleaseUnitTest
    - name: Check Output
      run: bash ./etc/CheckBuild/check-release.sh test
    - name: Sign APK
      run: bash ./etc/SignAPK/signapk.sh
    - name: Archive APKs
      uses: actions/upload-artifact@v2
      with:
        name: xDrip-release
        path: |
          xDrip-*-release.apk
